Py11: py::set Class Reference
py::set Class Reference
set object
#include <py11/_set.hpp>
Public Member Functions
set ()=default
ctor.
set (PyObject *p, bool borrowed=false)
create from Py functions.
set (std::initializer_list< obj > l)
ctor.
set operator& (const obj &o) const
op &.
set & operator&= (const obj &o)
op &=.
set operator| (const obj &o) const
op |.
set & operator|= (const obj &o)
op |=.
set operator- (const obj &o) const
op -.
set & operator-= (const obj &o)
op -=.
void add (const obj &o)
add an element.
void discard (const obj &o)
discard an element if present
void remove (const obj &o)
remove an element if present
obj pop ()
pop an element
void extend (const obj &o)
add elements from an iterable object.
void clear ()
clear.
Public Member Functions inherited from py::num
num ()=default
ctor.
num (PyObject *p, bool borrowed=false)
create from Py functions.
num operator+ (const obj &o) const
op +.
num & operator+= (const obj &o)
op +=.
num operator* (const obj &o) const
op *.
num & operator*= (const obj &o)
op *=.
num operator& (const obj &o) const
op &.
num & operator&= (const obj &o)
op &=.
num operator| (const obj &o) const
op |.
num & operator|= (const obj &o)
op |=.
num operator- (const obj &o) const
op -.
num & operator-= (const obj &o)
op -=.
Public Member Functions inherited from py::obj
obj (const obj &o) noexcept
copy ctor.
obj (PyObject *p, bool borrowed=false) noexcept
create from Py functions.
obj (obj &&o) noexcept
move ctor.
obj (std::initializer_list< obj > l)
tuple.
~obj () noexcept
dtor.
void release () noexcept
release the contained object
PyObject * transfer () noexcept
transfer the ownership of inner object.
bool is_null () const
test null.
bool operator! () const
is false
obj (int i)
int.
obj (long i)
long.
bool is_int () const
is_int.
long as_long () const
get long from obj
obj (double v)
double ctor.
bool is_float () const
is_float.
double as_double () const
as_double from obj.
obj (const char *s)
str.
const char * c_str () const
c_str().
obj type () const
py object type.
bool is_a (const obj &t) const
type check
bool has_attr (const obj &o) const
has attr.
bool has_attr (const char *s) const
has attr.
obj attr (const obj &o) const
get attr.
obj attr (const char *s) const
get attr.
obj a (const char *s) const
get attr, short form.
void set_attr (const obj &a, const obj &v)
set attr.
void set_attr (const char *a, const obj &v)
set attr.
void del_attr (const obj &a)
del attr.
void del_attr (const char *a)
del attr.
bool operator< (const obj &o) const
<
obj repr () const
repr.
obj to_str () const
str.
obj to_unicode () const
unicode.
bool is_callable () const
test callable.
template<typename... argT>
obj operator() (argT &&...a) const
call using operator.
obj call (const obj &args, const obj &kw) const
call with key/value pairs.
long size () const
'len' as 'size'.
bool has (const obj &x) const
'in' as 'has'.
const obj operator[] (const obj &o) const
get item.
void set_item (const obj &key, const obj &value)
set_item.
void del_item (const obj &key)
del_item.
iter begin () const
get the begin iter.
iter end () const
get the end iter.
obj dir () const
py object dir.
Py_ssize_t refcnt () const
refcnt.
PPyObject p () const
get inner PyObject.
Detailed Description
set object
Definition at line 5 of file _set.hpp.
Constructor & Destructor Documentation
py::set::set (PyObject * p, bool borrowed = false) inline
create from Py functions.
in most of cases, need not to inc ref. please read python doc carefully
Definition at line 61 of file _set.hpp.
References py::obj::p().
Member Function Documentation
void py::set::add (const obj & o) inline
add an element.
Exceptions
val_err
Definition at line 168 of file _set.hpp.
References py::obj::p().
Referenced by extend(), and set().
void py::set::discard (const obj & o) inline
discard an element if present
Exceptions
err
Definition at line 181 of file _set.hpp.
References py::obj::p().
set py::set::operator& (const obj & o) const inline
op &.
Exceptions
type_err
Definition at line 102 of file _set.hpp.
References py::obj::p().
set& py::set::operator&= (const obj & o) inline
op &=.
Exceptions
type_err
Definition at line 113 of file _set.hpp.
References py::obj::p().
set py::set::operator- (const obj & o) const inline
op -.
Exceptions
type_err
Definition at line 146 of file _set.hpp.
References py::obj::p().
set& py::set::operator-= (const obj & o) inline
op -=.
Exceptions
type_err
Definition at line 157 of file _set.hpp.
References py::obj::p().
set py::set::operator| (const obj & o) const inline
op |.
Exceptions
type_err
Definition at line 124 of file _set.hpp.
References py::obj::p().
set& py::set::operator|= (const obj & o) inline
op |=.
Exceptions
type_err
Definition at line 135 of file _set.hpp.
References py::obj::p().
obj py::set::pop () inline
pop an element
Exceptions
index_err if empty
err
Definition at line 205 of file _set.hpp.
void py::set::remove (const obj & o) inline
remove an element if present
Exceptions
index_err if not present
err
Definition at line 192 of file _set.hpp.
References py::obj::p().
The documentation for this class was generated from the following file:
/NoBackup/git/callpy/include/py11/_set.hpp