Py11: py::list Class Reference
py::list Class Reference
py list.
#include <py11/_list.hpp>
Public Member Functions
list ()=default
ctor.
list (PyObject *p, bool borrowed=false)
create from Py functions.
list (std::initializer_list< obj > l)
ctor.
list & operator= (std::initializer_list< obj > l)
= {...}
long size () const
'len' as 'size'.
bool has (const obj &x) const
'in' as 'has'.
long find (const obj &o) const
list find a item.
long index (const obj &o) const
list index.
tuple to_tuple () const
get a tuple clone.
const obj operator[] (Py_ssize_t i) const
get item.
void set_item (Py_ssize_t i, const obj &value)
set_item.
obj sub (int i, int j=std::numeric_limits< int >::max()) const
slice, [i:j].
void sort ()
sort in place.
void reverse ()
reverse in place.
void append (const obj &o)
append.
void insert (Py_ssize_t index, const obj &o)
insert.
Public Member Functions inherited from py::seq
seq ()=default
ctor.
seq (PyObject *p, bool borrowed=false)
create from Py functions.
seq (std::initializer_list< obj > l)
tuple.
seq operator+ (const obj &o) const
op +.
seq & operator+= (const obj &o)
op +=.
seq operator* (Py_ssize_t t) const
op *.
seq & operator*= (Py_ssize_t t)
op *=.
long size () const
'len' as 'size'.
bool has (const obj &x) const
'in' as 'has'.
long find (const obj &o) const
seq find a item.
long index (const obj &o) const
seq index.
list to_list () const
get a list clone.
tuple to_tuple () const
get a tuple clone.
const obj operator[] (Py_ssize_t i) const
get item.
void set_item (Py_ssize_t i, const obj &value) const
set_item.
void del_item (Py_ssize_t i)
del_item.
obj sub (int i, int j=std::numeric_limits< int >::max()) const
slice, [i:j].
Public Member Functions inherited from py::obj
obj (const obj &o) noexcept
copy ctor.
obj (PyObject *p, bool borrowed=false) noexcept
create from Py functions.
obj (obj &&o) noexcept
move ctor.
obj (std::initializer_list< obj > l)
tuple.
~obj () noexcept
dtor.
void release () noexcept
release the contained object
PyObject * transfer () noexcept
transfer the ownership of inner object.
bool is_null () const
test null.
bool operator! () const
is false
obj (int i)
int.
obj (long i)
long.
bool is_int () const
is_int.
long as_long () const
get long from obj
obj (double v)
double ctor.
bool is_float () const
is_float.
double as_double () const
as_double from obj.
obj (const char *s)
str.
const char * c_str () const
c_str().
obj type () const
py object type.
bool is_a (const obj &t) const
type check
bool has_attr (const obj &o) const
has attr.
bool has_attr (const char *s) const
has attr.
obj attr (const obj &o) const
get attr.
obj attr (const char *s) const
get attr.
obj a (const char *s) const
get attr, short form.
void set_attr (const obj &a, const obj &v)
set attr.
void set_attr (const char *a, const obj &v)
set attr.
void del_attr (const obj &a)
del attr.
void del_attr (const char *a)
del attr.
bool operator< (const obj &o) const
<
obj repr () const
repr.
obj to_str () const
str.
obj to_unicode () const
unicode.
bool is_callable () const
test callable.
template<typename... argT>
obj operator() (argT &&...a) const
call using operator.
obj call (const obj &args, const obj &kw) const
call with key/value pairs.
long size () const
'len' as 'size'.
bool has (const obj &x) const
'in' as 'has'.
const obj operator[] (const obj &o) const
get item.
void set_item (const obj &key, const obj &value)
set_item.
void del_item (const obj &key)
del_item.
iter begin () const
get the begin iter.
iter end () const
get the end iter.
obj dir () const
py object dir.
Py_ssize_t refcnt () const
refcnt.
PPyObject p () const
get inner PyObject.
Detailed Description
py list.
Definition at line 5 of file _list.hpp.
Constructor & Destructor Documentation
py::list::list (PyObject * p, bool borrowed = false) inline
create from Py functions.
in most of cases, need not to inc ref. please read python doc carefully
Definition at line 61 of file _list.hpp.
References py::obj::p().
Member Function Documentation
long py::list::find (const obj & o) const inline
list find a item.
Returns
index if found, -1 otherwise
Exceptions
type_err
Definition at line 133 of file _list.hpp.
References py::obj::p().
bool py::list::has (const obj & x) const inline
'in' as 'has'.
Exceptions
type_err
Definition at line 121 of file _list.hpp.
References py::obj::p().
long py::list::index (const obj & o) const inline
list index.
Returns
index if found
Exceptions
index_err if not found
type_err
Definition at line 144 of file _list.hpp.
References py::obj::p().
const obj py::list::operator[] (Py_ssize_t i) const inline
get item.
Warning, a new obj will be got! not a reference to the original one!
Exceptions
index_err
Definition at line 167 of file _list.hpp.
References py::obj::p().
void py::list::set_item (Py_ssize_t i, const obj & value) inline
set_item.
Exceptions
index_err
Definition at line 179 of file _list.hpp.
References py::obj::p().
long py::list::size () const inline
'len' as 'size'.
Exceptions
type_err
Definition at line 110 of file _list.hpp.
obj py::list::sub (int i, int j = std::numeric_limits<int>::max()) const inline
slice, [i:j].
Exceptions
type_err
Definition at line 189 of file _list.hpp.
References py::obj::p().
tuple py::list::to_tuple () const inline
get a tuple clone.
Exceptions
type_err
Definition at line 155 of file _list.hpp.
The documentation for this class was generated from the following file:
/NoBackup/git/callpy/include/py11/_list.hpp